// Generates src/version.ts with build-time version info.
// Run automatically before `dev` and `build` (see package.json scripts).
//   - version:  from package.json
//   - gitHash:  short commit hash (or 'dev' if not a git repo)
//   - buildTime: ISO timestamp of when this build ran
import { readFileSync, writeFileSync } from 'fs'
import { execSync } from 'child_process'

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'))

function gitHash() {
  try {
    return execSync('git rev-parse --short HEAD').toString().trim()
  } catch {
    return 'dev'
  }
}

const content = `// AUTO-GENERATED by scripts/version.mjs — do not edit by hand.
export const VERSION = '${pkg.version}'
export const GIT_HASH = '${gitHash()}'
export const BUILD_TIME = '${new Date().toISOString()}'
`

writeFileSync(new URL('../src/version.ts', import.meta.url), content)
console.log(`[version] v${pkg.version} @ ${gitHash()} (${new Date().toISOString()})`)
